### ISSUE TITLE
Tracking issue: Rustbuild submodule management can break nightlies

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust-central-station#11]
We had a brief outage of nightlies, which is Not Supposed to be Possible. 

The problem:

Rustbuild itself checks out submodules, but on CI that's not what we do. On CI a script manages submodules and then the build happens in a container where rustbuild takes over. 

It's possible to check in a change that breaks rustbuild submodule management, which means `./configure + make` is not guaranteed to work.

The change that broke in this instance was that a Cargo.toml that was a member of the rustbuild workspace was a member of a submodule, so for cargo to build rustbuild we needed to update submodules. To update submodules, though, we needed rustbuild. 🐍 🐍 

A fix has now been implemented to move submodule management to the x.py python script (src/bootstrap/bootstrap.py), so this hopefully won't happen again, but this issue is to track if it ever does so that @alexcrichton can eat his hat 🎩 and we can invest time in making rust-central-station even more like CI.

**Comment by alexcrichton** [comment]
Thanks for making an issue! So the surface problem here is likely mostly taken care of and is unlikely to resurface (submodule management). The core problem though is that producing a nightly requires running processes that are not tested as part of our CI. This means that things can break!

Overall to really squash this bug we need two separate pieces:

* As part of rust-lang/rust CI we need to produce the manifests that rust-central-station produces. I don't know how to do this with today's setup.
* We also need to CI rust-central-station itself as part of the rust-lang/rust build to ensure that everything works out in terms of deployment and whanot.
* Finally, we need more integration testing on rust-central-station itself to run it through its paces when making changes.

Unfortunately I don't really know how to do any of those. I was thinking we could add a CI builder which just publishes an older set of artifacts as a release to a dummy location, but that's not really solving the above problems because it's not (a) testing the master branch of rust-central-station or (b) testing the artifacts that are about to be produced by the build.

**Comment by pietroalbini** [comment]
This is fixed by [the new `promote-release`](https://github.com/rust-lang/promote-release), as it doesn't invoke rustbuild nor clone `rust-lang/rust` anymore. The new `promote-release` also features testing in CI.
