### ISSUE TITLE
Promotion should use a consistent date and time

### ISSUE THREAD

**Issue by aidanhs** [rust-lang/rust-central-station#50]
The sign-and-hash invocation on x.py calls `date`, but so does RCS on startup. If these straddle a new day, bad things happen.

One big hammer is to use `faketime` to fix the time at the top level and make every `date` command return the same value.

**Comment by aidanhs** [comment]
cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
I think perhaps the better way to fix this is to pull https://github.com/rust-lang/rust/tree/master/src/tools/build-manifest into this repo and then depend on it directly.

This will simplify x.py I think since we can then remove some configuration and a few other things -- `HashSign` is a really odd step anyway as-is today.

It's not completely trivial since there's some version ready x.py knows of but should be feasible and a good step to take.

**Comment by pietroalbini** [comment]
This is fixed by [the new `promote-release`](https://github.com/rust-lang/promote-release), since it passes the date it's using directly to `build-manifest`.
